[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "scraper"
version = "0.1.0"
description = "A simple Python scraping module"
dependencies = [
    "selenium"
]
